import { IChat } from "types/chat";

export default function cases(chat: IChat) {
	if (chat.command) console.log("Upsert Messages Log : ", chat);

	try {
		switch (chat.command) {
			case "hello_bot":
				chat.replay({
					text: "💬 Hi there! This reply was generated by Bot.\n\n_*111CodeLabs*_",
				});
				break;

			default:
				break;
		}
	} catch (error) {
		console.log(error);
	}
}
